# Generated by Django 4.1.4 on 2023-01-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=20)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('publisted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
