# Generated by Django 4.1.4 on 2023-01-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_header', models.ImageField(upload_to='')),
                ('kategori', models.CharField(max_length=20)),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('nama', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
