# Generated by Django 4.1.4 on 2023-01-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('lead', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('start', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
                ('progres', models.CharField(max_length=200)),
                ('hp', models.CharField(max_length=200)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
