# Generated by Django 4.1.4 on 2023-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='start',
            field=models.DateField(),
        ),
    ]
