# Generated by Django 4.1.4 on 2023-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_monitor_end_alter_monitor_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='progres',
            field=models.IntegerField(max_length=100),
        ),
    ]
