# Generated by Django 4.1.4 on 2022-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('kategori', models.TextField()),
                ('judul', models.CharField(max_length=255)),
                ('kontent', models.TextField()),
            ],
        ),
    ]
