# Generated by Django 4.1.4 on 2023-01-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontenmodel',
            name='jenis',
        ),
        migrations.AddField(
            model_name='kontenmodel',
            name='jenis',
            field=models.ManyToManyField(to='relasi.kategorimodel'),
        ),
    ]
