# Generated by Django 4.1.4 on 2023-01-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relasi', '0003_alter_kontenmodel_jenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontenmodel',
            old_name='jenis',
            new_name='kategori',
        ),
    ]
