# Generated by Django 4.1.4 on 2023-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relasi', '0004_rename_jenis_kontenmodel_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontenmodel',
            name='kategori',
            field=models.ManyToManyField(to='relasi.kategorimodel'),
        ),
    ]
