# Generated by Django 4.1.4 on 2022-12-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='judul',
            field=models.CharField(default='post', max_length=255),
        ),
    ]
