# Generated by Django 4.1.4 on 2023-01-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_projek', models.CharField(max_length=20)),
                ('lead', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='')),
                ('nama', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
