# Generated by Django 4.1.4 on 2023-01-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apimodel',
            name='foto',
        ),
    ]
