# Generated by Django 4.1.4 on 2023-01-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('kategori', models.CharField(max_length=20)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=4)),
                ('keterangan', models.TextField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
